### ISSUE TITLE
 Could not find :af-android-sdk-4.8.3

### ISSUE THREAD

**Issue by captainhaddock29** [AppsFlyerSDK/nativescript-plugin-appsflyer#10]
Hi,
I have a problem when I want to build a project with this plugin : 

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_F0DebugApkCopy'.
   > Could not find :af-android-sdk-4.8.3:.
     Required by:
         project :app

Can you give me some guidance into what is it that I'm doing wrong?
Thanks !

**Comment by af-fess** [comment]
@captainhaddock29 Please give relevant info about your environment. What `tns` version do you use, `npm`, ....

please check my answer: https://stackoverflow.com/a/49157360/1631379

**Comment by captainhaddock29** [comment]
I have followed your procedure, but same result : 

    * What went wrong:
    A problem occurred configuring project ':app'.
    > Could not resolve all dependencies for configuration ':app:_F0DebugApkCopy'.
       > Could not find :af-android-sdk-4.8.3:.
         Required by:
             project :app

Versions : 

    tns --version // 3.4.3
    npm -v // 5.6.0
    node -v //v8.9.4

I've tried to downgrade tns to 3.2.1 but same error, again.

**Comment by captainhaddock29** [comment]
And same problem when I try to open the android project with Android Studio : 
` Error:Failed to resolve: :af-android-sdk-4.8.3:`

**Comment by af-fess** [comment]
@captainhaddock29 you are right. After upgrading `tns` from `3.2.1` to `3.4.3` i started to get the same error:

![screen shot 2018-03-08 at 4 01 17 pm](https://user-images.githubusercontent.com/22323472/37155974-63a33fec-22ed-11e8-881a-fbcc924ed397.png)


I opened ticket to NativeScript:
https://github.com/NativeScript/NativeScript/issues/5514

**Comment by captainhaddock29** [comment]
Thanks !

**Comment by af-fess** [comment]
@captainhaddock29  please see workround till it will be fixed (next week suppose):

https://github.com/NativeScript/NativeScript/issues/5514#issuecomment-371736800
