### ISSUE TITLE
Compiles OK on iOS but not on Android

### ISSUE THREAD

**Issue by danazkari** [AppsFlyerSDK/nativescript-plugin-appsflyer#8]
Hello! 

I'm working on an app that uses this plugin, works perfectly fine when we build for iOS but when building for Android, gradle complains about not being able to find the required plugin:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_F0F1F2F3F4F5F6F7DebugApkCopy'.
   > Could not find :af-android-sdk-4.8.3:.
     Required by:
         project :app
```

I reproduced the issue on a blank newly created project here:
[![asciicast](https://asciinema.org/a/160836.png)](https://asciinema.org/a/160836)

I recorded the ZSH session so you can see all of the steps I went through.

Can you give me some guidance into what is it that I'm doing wrong? My `tns --version` is 3.4.2 BTW.

Thanks!

**Comment by danazkari** [comment]
Heyo! If you guys want me to, I could start poking around to see if I can find the cause and perhaps even the fix for this issue and create a PR, please let me know if you have any pointers that might help me solve this issue quicker.

Thanks!!

**Comment by danazkari** [comment]
After a few tests, I realized that the problem is related to the version of Android we were using, so I guess the issue is with tns-android version 3.3.0, we bumped it down to 3.2.0 and it worked.

**Comment by captainhaddock29** [comment]
Hi, 
I have the same problem : 

```
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_F0DebugApkCopy'.
   > Could not find :af-android-sdk-4.8.3:.
     Required by:
         project :app
```
I tried to downgrade tns to 3.2.0 but same error. 

Can you give me some guidance into what is it that I'm doing wrong?
Thanks !

**Comment by af-fess** [comment]
loads Native SDK from maven: https://github.com/AppsFlyerSDK/nativescript-plugin-appsflyer/commit/3b4e27533f30daf253f7500a13485af3524c2ea1

Thanks
